/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentación;


import Datos.DAsignatura;
import Lógica.LCursosEstudiantes;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmCursosEstudiante extends javax.swing.JInternalFrame {
    
    private final int id_usuario;
    private final LCursosEstudiantes logica;
    
    public FrmCursosEstudiante(int id_usuario) {
        initComponents();
        DefaultTableModel modeloCorrecto = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Curso", "Asignatura"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        TablaCursosEstudiante.setModel(modeloCorrecto);
        this.id_usuario = id_usuario;
        this.logica = new LCursosEstudiantes();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mis Asignaturas");
        setVisible(true);
        cargarAsignaturas();
    }
    
    private void cargarAsignaturas() {
        DefaultTableModel modelo = (DefaultTableModel) TablaCursosEstudiante.getModel();
        modelo.setRowCount(0);

        String nombreEstudiante = logica.obtenerNombreEstudiante(id_usuario);
        String nombreCurso = logica.obtenerNombreCursoEstudiante(id_usuario);

        if (nombreCurso == null) {
            JOptionPane.showMessageDialog(this, "No estás inscrito en ningún curso.");
            return;
        }

        List<DAsignatura> lista = logica.listarAsignaturasPorEstudiante(id_usuario);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay asignaturas para tu curso.");
            return;
        }

        for (DAsignatura a : lista) {
            modelo.addRow(new Object[]{id_usuario, nombreEstudiante, nombreCurso, a.getNombre()});
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCursosEstudiante = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        TablaCursosEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCursosEstudiante.setPreferredSize(new java.awt.Dimension(600, 400));
        jScrollPane1.setViewportView(TablaCursosEstudiante);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCursosEstudiante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
